version: "3.9"

services:
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
      authelia:
        condition: service_healthy
    networks:
      - frontend
      - backend
    environment:
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - DOMAIN=https://vault.${DOMAIN}
    volumes:
      - ${DB_BASE}/vaultwarden:/data${VOLUME_OPTS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vw.rule=Host(`vault.${DOMAIN}`)"
      - "traefik.http.routers.vw.entrypoints=web"
      - "traefik.http.services.vw.loadbalancer.server.port=80"

      # Protect /admin behind Authelia SSO
      - "traefik.http.routers.vw-admin.rule=Host(`vault.${DOMAIN}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.vw-admin.entrypoints=web"
      - "traefik.http.routers.vw-admin.priority=100"
      - "traefik.http.routers.vw-admin.middlewares=authelia-https@docker,authelia@docker"
      - "traefik.http.routers.vw-admin.service=vw@docker"
